#!/usr/bin/env python3
from __future__ import annotations

import json
import pathlib
import sys


def arg_value(name: str, default: str | None = None) -> str | None:
    if name not in sys.argv:
        return default
    index = sys.argv.index(name)
    if index + 1 >= len(sys.argv):
        return default
    return sys.argv[index + 1]


def main() -> int:
    game_dir = arg_value("--cd")
    last_path = arg_value("--output-last-message")

    prompt = sys.stdin.read()

    if not game_dir or not last_path:
        print("missing args", file=sys.stderr)
        return 1

    game_path = pathlib.Path(game_dir)
    game_path.mkdir(parents=True, exist_ok=True)

    index_html = game_path / "index.html"
    index_html.write_text(
        """<!doctype html>
<html>
  <body>
    <h1>Generated by fake codex</h1>
    <pre id='prompt'></pre>
    <script>document.getElementById('prompt').textContent = window.__PROMPT__ || 'ok';</script>
  </body>
</html>
""",
        encoding="utf-8",
    )

    pathlib.Path(last_path).write_text(
        "Fake codex completed successfully.",
        encoding="utf-8",
    )

    events = [
        {"event": "run_started"},
        {"event": "assistant_message", "content": "Building game files..."},
        {"event": "run_completed", "content": "Done"},
    ]

    for event in events:
        print(json.dumps(event), flush=True)

    if "FAIL_FAKE_CODEX" in prompt:
        print("forced failure", file=sys.stderr, flush=True)
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
